version: '2.1'
volumes: 
  workspace:
services:
  runner:
    build: .
    volumes:
      - workspace:/data
    privileged: true
    network_mode: host
    environment:
      - UDEV=1
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.balena-api: '1'
      io.balena.features.kernel-modules: '1'
